Output demo.gif

Set FontSize 20
Set Width 960
Set Height 540
Set FontFamily "SauceCodePro Nerd Font Mono"
Set Theme "Gruvbox Dark"
Set Padding 20
Set Shell zsh

Hide
Type "clear"
Enter
Sleep 1s
Show

Sleep 1s

Type "mpcube"

Sleep 500ms

Enter

Sleep 3s

Set TypingSpeed 500ms 
Type "jjj"

Sleep 1s
Type "l"
Sleep 1s

Enter
Sleep 2s

Type "nnnnn"
Sleep 5s

Set TypingSpeed 1s
Type '--==...,,,srsr'

Sleep 3s
